services:
  backend:
    build:
      context: ./backend
    container_name: weather-backend
    ports:
      - "8081:8080"
    environment:
      - WEATHER_API_KEY=${WEATHER_API_KEY}
      - OFFLINE_MODE=${OFFLINE_MODE}
    networks:
      - weather-network

  weather-ui:
    build:
      context: ./weather-ui
    container_name: weather-ui
    image: forecast-weather-ui
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - weather-network

networks:
  weather-network:
    driver: bridge