services:
  weather-service:
    image: weather-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - weather.offline-mode=false
      - weather.api.key=641592fe6d94cc07de6d27c9a67d1f0b