services:
  weather-service:
    image: weather-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      - WEATHER_OFFLINE_MODE=false
      - WEATHER_API_KEY=641592fe6d94cc07de6d27c9a67d1f0b