server:
  port: 8080

spring:
  application:
    name: forecast

weather:
  api:
    url: https://api.openweathermap.org/data/2.5/forecast
    key: 641592fe6d94cc07de6d27c9a67d1f0b
    count: 40
  offline-mode : false

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html